platform :ios, '9.0'

target 'OCMockitoSwift' do
  use_frameworks!

  target 'OCMockitoSwiftTests' do
    inherit! :search_paths
    pod 'OCMockitoSwift', :path => '../'
    pod 'OCMockito'
    pod 'Quick'
    pod 'Nimble'
  end

end
